### ISSUE TITLE
Profile-page, 'wrong' name shown

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#160]
on the left top, it says 'Welcome to your new Profile, default'. 

Apparently the Personal-Details > Name is shown,
However, i have set all the setting in Privacy to 'Show my username'.
In this case i would expect to see my username (particularly important if you make screenprints to share on social media).

(however, maybe we also are missing a setting with which you can say what name you want to display in this screen).

**Comment by GeniJaho** [comment]
@FredMark I think this one is solved too. I can always see my full name on the profile page, regardless of the privacy settings. Even on the code, it shows directly the name, without checking for privacy settings. Can we close this issue?

**Comment by FredMark** [comment]
@GeniJaho 
You're right!
It still shows 'Welcome to your new Profile, default',
but if i go to the settings page, 'default' turns out to be the setting for 'Personal Details > Your name',
And at this moment it is possible to change that name and that reflects on the profilepage, so indeed, this one is working correctly, i only have to change the settings ('your name') in the profile page.
Thanks, this one can be closed!
